version: 2
jobs:
  build:
    docker:
      - image: segment/golang:latest
    working_directory: /go/src/github.com/segmentio/ecs-logs
    steps:
      - checkout
      - run:
          name: install necessary packages
          command: apt-get update && apt-get -y install rubygems ruby-dev
      - run:
          name: check out dependencies
          command: make depend
      - run:
          name: test
          command: make test
      - run:
          name: build package
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              make deb
              make upload_deb
            fi
      - setup_remote_docker
      - run:
          name: build Docker image
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              make image
              make push_image
            fi
