version: 2
jobs:
  build:
    docker:
      - image: segment/golang:latest
    working_directory: /go/src/github.com/segmentio/ecs-logs
    steps:
      - checkout
      - run:
          name: check out dependencies
          command: make dep
      - run:
          name: test
          command: make test
      - run:
          name: build package
          command: make deb
