version: 2
jobs:
  build:
    docker:
      - image: segment/golang:latest
    working_directory: /go/src/github.com/segmentio/ecs-logs
    steps:
      - checkout
      - run:
          name: install necessary packages
          command: apt-get update && apt-get -y install rubygems ruby-dev
      - run:
          name: check out dependencies
          command: make depend
      - run:
          name: test
          command: make test
      - run:
          name: build package
          command: make deb
