version: 2
jobs:
  build:
    docker:
      - image: segment/golang:latest
    working_directory: /go/src/github.com/segmentio/ecs-logs
    steps:
      - checkout
      - run:
          name: install necessary packages
          command: apt-get update && apt-get -y install rubygems ruby-dev
      - run:
          name: check out dependencies
          command: make depend
      - run:
          name: test
          command: make test
      - run:
          name: build package
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ] && git describe --tags --exact-match >/dev/null 2>&1; then
              echo "{\"url\":\"https://packagecloud.io\",\"token\":\"$PACKAGECLOUD_TOKEN\"}" > $HOME/.packagecloud
              make deb
              make upload_deb
            else
              echo "Skipped"
            fi
      - setup_remote_docker
      - run:
          name: build Docker image
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ] && git describe --tags --exact-match >/dev/null 2>&1; then
              make image
              make push_image
            else
              echo "Skipped"
            fi
